spring.application.name=cab-service
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/cabService
spring.datasource.username=postgres
spring.datasource.password=anirudh
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update